### ISSUE TITLE
Cut off Chunks

### ISSUE THREAD

**Issue by CptCrispyCrunchy** [Terasology/ShatteredPlanes#3]
As already mentioned in [Terasology/issues/2260](https://github.com/MovingBlocks/Terasology/issues/2260) some chunks are cutoff. This will result in truncated trees and mountains and is especially visible at y=64 in this worldgenerator. 
The odd thing is, that it seems to only affect this worldgenerator even though ShatteredPlanes uses core world gen stuff. 
At the moment my main lead is that the surfaceheightfacet has a large amount of update passes which could lead to some stuff getting messed up somehow. So I'll try some different providerchain setups.
In the worst case I can imagine, the rasterizers are doing their job lets say for the chunk above y=64 at a certain position while the chunk below y=64 is still cycling through the facetproviders. However when the rasterizer process begins in the chunk below, the surfaceheight suddenly reaches into the chunk above it. Thus it rasterizers only exactly to y=64 and stops there as the chunk above is already seen as fully rasterized.

I haven't looked at the rasterizer process in detail in the engine code yet. To test the last idea, it would be nice to create a world synchronized for this special case. 

Maybe someone with deeper knowledge of the engine code could comment whether this is worth looking into.

**Comment by jdrueckert** [comment]
Wasn't able to reproduce it. Looking at the time this was reported, I'll call this "probably fixed by now" and close the issue until we observe anything like this again.
